4.11. Домашнее задание - Расчёты и math
d-nekrasov/purple-school-homework pull request #5
Opened 2024-03-31 16:22 UTC by d-nekrasov

2024-03-31 19:44 UTC, Levitinn requested changes

2024-03-31 19:44 UTC, Levitinn commented on js/dice.js
> +function throwDice(type){
не годится. твоя функция принимает любой тип, а поддерживаться должны только описанные.

2024-04-05 15:50 UTC, d-nekrasov commented on js/dice.js
> +function throwDice(type){
Добавил массив `dices ` со списком дайсов, которые поддерживаются. Если нет в массиве переданного дайса -функция возвращает `false`. Так же сделал дефолтное значение, если в функцию `throwDice` не передать аргумент,  она по дефолту будет работать с D4

2024-04-06 20:38 UTC, Levitinn requested changes

2024-04-06 20:38 UTC, Levitinn commented on js/dice.js
> +    const dices = ['D4', 'D6', 'D8', 'D10', 'D12', 'D16', 'D20'];
решение рабочее, но не самое лучшее, если использовать объект с ключами 'D4', 'D6',.... то можно будет избавиться от методов которые проходят циклом при каждом использовании

2024-04-07 09:46 UTC, d-nekrasov commented on js/dice.js
> +    const dices = ['D4', 'D6', 'D8', 'D10', 'D12', 'D16', 'D20'];
Выполнил оптимизацию. Теперь вместо массива объект дайсов и проверка на наличие свойства в объекте

2024-04-08 19:41 UTC, Levitinn approved these changes

2024-04-08 20:39 UTC, merged