5.7. Домашнее задание - Даты и время
d-nekrasov/purple-school-homework pull request #6
Opened 2024-03-31 16:22 UTC by d-nekrasov

2024-03-31 19:48 UTC, Levitinn requested changes

2024-03-31 19:48 UTC, Levitinn commented on js/birthday.js
> +function ageValidate (date) {
нет проверки на месяц и день в году

2024-04-05 17:26 UTC, d-nekrasov commented on js/birthday.js
> +function ageValidate (date) {
Доработал код, теперь  помимо сравнения года проверяется еще и месяц, если месяц совпадает проверяется день

2024-04-06 20:38 UTC, Levitinn approved these changes

2024-04-07 09:34 UTC, merged