6.7. Домашнее задание - Таймеры
d-nekrasov/purple-school-homework pull request #7
Opened 2024-04-07 14:54 UTC by d-nekrasov

2024-04-08 19:44 UTC, Levitinn requested changes

2024-04-08 19:44 UTC, Levitinn commented on js/timer.js
в целом все неплохо, но давай посмотрим со стороны разработки на реальном проекте. для того чтобы твой код, использовать где то в другом месте проекта, нужно будет скопипастить весь код в другой файл. А гораздо удобнее, если это будет одна функция, которую можно использовать в любом месте проекта. 
Засунь всю логику таймера внутрь одной функции, при вызове которой будет запускаться таймер

2024-04-14 07:29 UTC, d-nekrasov commented on js/timer.js
Внес изменения на основе комментария

2024-04-15 08:36 UTC, AlariCode commented on js/timer.js
@d-nekrasov  Так как Никита в отпуске, глянул код, исправление принимается, можешь вливать

2024-04-16 15:28 UTC, merged